name: Python and Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requisitos.txt

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
  
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0' # La versión de Flutter que estás utilizando

    - name: Build with Flet
      run: |
        flet build apk 

    - name: Create Release
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: |
          build/
          dist/
          bin/
          lib/
          include/
          src/
        if-no-files-found: error
